server:
  port: 8099
spring:
    application:
        name: service_test1_name
    datasource:
        name: test
       # url: jdbc:mysql://localhost:3306/mybatis
        url: jdbc:mysql://localhost:3306/test_sql
        username: root
        password: root
        # 使用druid数据源
        #type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver


## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  #type-aliases-package: com.winter.model  # 注意：对应实体类的路径
  configuration:
        map-underscore-to-camel-case: true
        default-fetch-size: 100
        default-statement-timeout: 30
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

eureka:
  instance:
    prefer-ip-address: false
    appname: service_test1_appname
  client:
    serviceUrl:
      #defaultZone: http://peer1:8091/eureka/,http://peer2:8092/eureka/
      defaultZone: http://peer1:8091/eureka/